### ISSUE TITLE
Интерактивная ёфикация в спорных случаях

### ISSUE THREAD

**Issue by dima74** [e2yo/eyo#16]
Спасибо за ёфикатор! Добавьте, пожалуйста, возможность интерактивной ёфикации для спорных случаев. То есть вывод спорного слова с контекстом (несколько слов рядом с словом), считывание клавиши принятия/непринятия замены и на основе этого принимать решение о произведении замены.

**Comment by hcodes** [comment]
Хорошая идея.

**Comment by anton-petrunin** [comment]
Достаточно была такая опция:  в спорных случая делалась бы замена на что-то типа "ЁЕ" и тогда можно было бы легко найти и исправить в файле.
