### ISSUE TITLE
звёздчатый

### ISSUE THREAD

**Issue by anton-petrunin** [e2yo/eyo#20]
Вроде слова «звёздчатый» нет в словаре (?)

**Comment by dima74** [comment]
Кажется здесь не всё так однозначно: https://rus.stackexchange.com/q/441068/186424

**Comment by anton-petrunin** [comment]
Ну многогранник точно звёзчатый --- не будет он звезчАтым никогда...

**Comment by hcodes** [comment]
http://slovana.ru/slovari/reznichenko/orfoepicheskij-slovar-reznichenko_0340.htm

**Comment by hcodes** [comment]
Внёс слово в небезопасный словарь.
https://github.com/e2yo/eyo-kernel/pull/16
